"""Initial schema

Revision ID: a2f69a1173fd
Revises: 
Create Date: 2026-07-01 16:40:36.438457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2f69a1173fd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('currency', sa.String(), nullable=True))
    op.alter_column('payments', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False,
               comment='Unique transaction ID',
               autoincrement=True)
    op.alter_column('payments', 'amount',
               existing_type=sa.NUMERIC(),
               type_=sa.Float(),
               nullable=False,
               comment='Payment amount must be positive')
    op.alter_column('payments', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.drop_column('payments', 'userId')
    op.drop_column('payments', 'body')
    op.drop_column('payments', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('title', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('payments', sa.Column('body', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('payments', sa.Column('userId', sa.BIGINT(), autoincrement=False, nullable=True))
    op.alter_column('payments', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('payments', 'amount',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               nullable=True,
               comment=None,
               existing_comment='Payment amount must be positive')
    op.alter_column('payments', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True,
               comment=None,
               existing_comment='Unique transaction ID',
               autoincrement=True)
    op.drop_column('payments', 'currency')
    # ### end Alembic commands ###
